In [19]:
import numpy as np

In [20]:
x = [1.4, 2.5, -3.5, -3.5, 2.9, 5.3, 15, -13]

In [21]:
nps = np.array(x)
nps

array([  1.4,   2.5,  -3.5,  -3.5,   2.9,   5.3,  15. , -13. ])

In [22]:
nps.mean()

0.8875

In [23]:
nps - nps.mean()

array([  0.5125,   1.6125,  -4.3875,  -4.3875,   2.0125,   4.4125,
        14.1125, -13.8875])

In [24]:
np.abs(nps - nps.mean()).mean()

5.6656249999999995

In [25]:
(nps - nps.mean()) / np.abs(nps - nps.mean()).mean()

array([ 0.0904578 ,  0.28461114, -0.77440706, -0.77440706,  0.35521236,
        0.77881964,  2.49089906, -2.45118588])