In [12]:
import numpy as np
import pandas as pd

from src import akeneo, akeneo_clustering as ac

In [2]:
cache = akeneo.create_cache_from_env()

In [14]:
attr_df = pd.DataFrame(cache.attributes)
attr_df["typeclass"] = attr_df["type"].map(ac.map_to_attribute_kind)

In [28]:
attr_df[attr_df["group"] == "faulty"]

code                                             labels  \
6     icecat_1024  {'de_DE': 'Lautsprecher', 'en_GB': 'Speakers',...   
22   icecat_12435  {'de_DE': 'Auflösung Rückkamera (numerisch)', ...   
24   icecat_12437  {'de_DE': 'Auflösung Frontkamera (numerisch)',...   
29   icecat_13246  {'de_DE': 'Pixeldichte', 'en_GB': 'Pixel densi...   
31   icecat_13248  {'de_DE': 'Soziale Netzwerkdienste unterstützt...   
..            ...                                                ...   
401   icecat_8072  {'de_DE': 'Schutzfunktion', 'en_GB': 'Protecti...   
406   icecat_8367  {'de_DE': 'unterstützte 3G-Bandbreiten', 'en_G...   
419   icecat_8745  {'de_DE': 'Videoaufnahme-Modi', 'en_GB': 'Vide...   
425    icecat_898  {'de_DE': 'Material', 'en_GB': 'Material', 'en...   
445   icecat_9780  {'de_DE': 'Unterstützte Google-Anwendungen', '...   

                            type  localizable  scopable  unique   group  \
6             AttributeType.TEXT         True      True   False  faulty   
22            AttributeType.TEXT         True      True   False  faulty   
24            AttributeType.TEXT         True      True   False  faulty   
29            AttributeType.TEXT         True      True   False  faulty   
31   AttributeType.SELECT_SINGLE         True      True   False  faulty   
..                           ...          ...       ...     ...     ...   
401  AttributeType.SELECT_SINGLE         True      True   False  faulty   
406  AttributeType.SELECT_SINGLE         True      True   False  faulty   
419  AttributeType.SELECT_SINGLE         True      True   False  faulty   
425  AttributeType.SELECT_SINGLE         True      True   False  faulty   
445  AttributeType.SELECT_SINGLE         True      True   False  faulty   

                                          group_labels  sort_order  \
6    {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...        1024   
22   {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...       12435   
24   {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...       12437   
29   {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...       13246   
31   {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...       13248   
..                                                 ...         ...   
401  {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...        8072   
406  {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...        8367   
419  {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...        8745   
425  {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...         898   
445  {'en_US': 'Faulty', 'en_GB': 'Faulty', 'de_DE'...        9780   

    allowed_extensions  ... metric_family minimum_input_length  \
6                   []  ...          None                 None   
22                  []  ...          None                 None   
24                  []  ...          None                 None   
29                  []  ...          None                 None   
31                  []  ...          None                 None   
..                 ...  ...           ...                  ...   
401                 []  ...          None                 None   
406                 []  ...          None                 None   
419                 []  ...          None                 None   
425                 []  ...          None                 None   
445                 []  ...          None                 None   

    negative_allowed number_min number_max reference_data_name  \
6               None       None       None                None   
22              None       None       None                None   
24              None       None       None                None   
29              None       None       None                None   
31              None       None       None                None   
..               ...        ...        ...                 ...   
401             None       None       None                None   
406             None       None       None                None   
419             Non

In [34]:
attr_df[
    (attr_df["group"] != "faulty") &
    attr_df["code"].isin(cache.families[0].attributes) &
    attr_df["code"].isin(cache.families[1].attributes)
    # attr_df["code"].isin(cache.families[1].attribute_requirements["default"])
][["code", "typeclass"]].groupby("typeclass").count()

code
typeclass              
ID                    1
IMAGE                 1
TEXTAREA              2
categorical           1
multi-categorical     3
numerical            10
string               10

In [10]:
cache.families[0].attributes

['ean',
 'icecat_12935',
 'icecat_1464',
 'icecat_15767',
 'icecat_1649',
 'icecat_1650',
 'icecat_19016',
 'icecat_22044',
 'icecat_22615',
 'icecat_22656',
 'icecat_22658',
 'icecat_22660',
 'icecat_22661',
 'icecat_22662',
 'icecat_22663',
 'icecat_23047',
 'icecat_26241',
 'icecat_2646',
 'icecat_2757',
 'icecat_27575',
 'icecat_27575_fixed',
 'icecat_37637',
 'icecat_37638',
 'icecat_38163',
 'icecat_38164',
 'icecat_38673',
 'icecat_3889',
 'icecat_40020',
 'icecat_41305',
 'icecat_41308',
 'icecat_41309',
 'icecat_41381',
 'icecat_42512',
 'icecat_42513',
 'icecat_42513_fixed',
 'icecat_42514',
 'icecat_42514_fixed',
 'icecat_42515',
 'icecat_42516',
 'icecat_42516_fixed',
 'icecat_42521',
 'icecat_42521_fixed',
 'icecat_44462',
 'icecat_4456',
 'icecat_4457',
 'icecat_4463',
 'icecat_4463_fixed',
 'icecat_4860',
 'icecat_5197',
 'icecat_5516',
 'icecat_6767',
 'icecat_8006',
 'icecat_8156',
 'icecat_8411',
 'icecat_8778',
 'icecat_890',
 'icecat_898',
 'icecat_898_fixed',
 'ice

In [20]:
x = [1.4, 2.5, -3.5, -3.5, 2.9, 5.3, 15, -13]

In [21]:
nps = np.array(x)
nps

array([  1.4,   2.5,  -3.5,  -3.5,   2.9,   5.3,  15. , -13. ])

In [22]:
nps.mean()

0.8875

In [23]:
nps - nps.mean()

array([  0.5125,   1.6125,  -4.3875,  -4.3875,   2.0125,   4.4125,
        14.1125, -13.8875])

In [24]:
np.abs(nps - nps.mean()).mean()

5.6656249999999995

In [25]:
(nps - nps.mean()) / np.abs(nps - nps.mean()).mean()

array([ 0.0904578 ,  0.28461114, -0.77440706, -0.77440706,  0.35521236,
        0.77881964,  2.49089906, -2.45118588])